/* eslint-disable import/order */
/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable consistent-return */

// * Ejecutar con: DEBUG=app:* node scriptEjecutar

const MongoLib = require('../lib/mongoDB');
const chalk = require('chalk');
const debug = require('debug')('app:scripts:questions');

const uploadDataUny = [
  {
    nombreU: 'Carreras Universitarias en la Universidad Católica de Cuenca',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Física y Química',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de Cuenca',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad del Azuay',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Biológicas',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Politécnica Salesiana',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Seguridad, Criminología y Estudios Forenses',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Estatal de Bolívar',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Medio Ambiente y Geología',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Nacional de Educación',
    carrera: ['Educación'],
    area: ['ciencias sociales'],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Politécnica Estatal del Carchi',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Comercio y Relaciones Internacionales',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Salud y Medicina',
      'Transporte y Logística',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Escuela Superior Politécnica del Chimborazo',
    carrera: [
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Contabilidad',
      'Electrónica y Electricidad',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Transporte y Logística',
      'Veterinaria',
    ],
    area: [
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Nacional de Chimborazo',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Idiomas',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Técnica de Cotopaxi',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Medio Ambiente y Geología',
      'Publicidad, Marketing y RRPP',
      'Recursos Humanos y Riesgo Laboral',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'arte y creatividad',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Técnica de Machala',
    carrera: [
      'Administración y Administración Pública',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Políticas',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Técnica Luis Vargas Torres de Esmeraldas',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Contabilidad',
      'Deportes y Educación Física',
      'Educación',
      'Electrónica y Electricidad',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Medio Ambiente y Geología',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Escuela Superior Politécnica del Litoral',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Electrónica y Electricidad',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Nutrición y Alimentación',
      'Transporte y Logística',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en el Instituto Superior Tecnológico Simón Bolívar',
    carrera: ['Ingeniería y Tecnología'],
    area: ['ciencia y tecnología'],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Agraria del Ecuador',
    carrera: [
      'Ciencias Agrarias',
      'Informática e Información',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Veterinaria',
    ],
    area: [
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Casa Grande',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Políticas',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Educación',
      'Recursos Humanos y Riesgo Laboral',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Católica de Santiago de Guayaquil',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Ingeniería y Tecnología',
      'Lengua y Literatura',
      'Matemática, Economía y Finanzas',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad de Especialidades Espíritu Santo',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Hotelería, Gastronomía y Turismo',
      'Imagen y Sonido',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'arte y creatividad',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de Guayaquil',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de las Artes',
    carrera: ['Arte y Bellas Artes', 'Lengua y Literatura'],
    area: ['arte y creatividad', 'ciencias sociales'],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad del Pacífico',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Políticas',
      'Comercio y Relaciones Internacionales',
      'Contabilidad',
      'Derecho y Leyes',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Recursos Humanos y Riesgo Laboral',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Del Río',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Comercio y Relaciones Internacionales',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Publicidad, Marketing y RRPP',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'económica,administrativa y financiera',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'arte y creatividad',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Estatal de Milagro',
    carrera: [
      'Administración y Administración Pública',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Nutrición y Alimentación',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Laica Vicente Rocafuerte de Guayaquil',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Idiomas',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'arte y creatividad',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Metropolitana del Ecuador',
    carrera: [
      'Arquitectura Moda y Diseño',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Matemática, Economía y Finanzas',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Transporte y Logística',
    ],
    area: [
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Santa María',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Comercio y Relaciones Internacionales',
      'Informática e Información',
      'Matemática, Economía y Finanzas',
      'Publicidad, Marketing y RRPP',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'económica,administrativa y financiera',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'arte y creatividad',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Tecnológica Ecotec',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Recursos Humanos y Riesgo Laboral',
      'Salud y Medicina',
      'Seguridad, Criminología y Estudios Forenses',
      'Transporte y Logística',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Tecnológica Empresarial de Guayaquil',
    carrera: [
      'Administración y Administración Pública',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Recursos Humanos y Riesgo Laboral',
      'Seguridad, Criminología y Estudios Forenses',
      'Transporte y Logística',
    ],
    area: [
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de Otavalo',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Ingeniería y Tecnología',
      'Psicología y Ciencias del Comportamiento',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Técnica del Norte',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Yachay Tech',
    carrera: [
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Física y Química',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
    ],
    area: [
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en el Instituto Tecnológico Superior Sudamericano',
    carrera: ['Publicidad, Marketing y RRPP'],
    area: ['arte y creatividad'],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Nacional de Loja',
    carrera: [
      'Administración y Administración Pública',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Técnica Particular de Loja',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
      'Seguridad, Criminología y Estudios Forenses',
      'Transporte y Logística',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Técnica de Babahoyo',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Técnica Estatal de Quevedo',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Contabilidad',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Escuela Superior Politécnica Agropecuaria de Manabí',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Estatal del Sur de Manabí',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Comercio y Relaciones Internacionales',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Laica Eloy Alfaro de Manabi',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Idiomas',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad San Gregorio de Portoviejo',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Informática e Información',
      'Matemática, Economía y Finanzas',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Técnica de Manabi',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Bibliotecología y Archivología',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Ciencias Sociales y Humanidades',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Idiomas',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Regional Amazónica IKIAM',
    carrera: [
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Educación',
      'Medio Ambiente y Geología',
    ],
    area: [
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en Saint Leo University',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Sociales y Humanidades',
      'Contabilidad',
      'Ingeniería y Tecnología',
      'Psicología y Ciencias del Comportamiento',
      'Recursos Humanos y Riesgo Laboral',
      'Transporte y Logística',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Kuepa',
    carrera: [
      'Administración y Administración Pública',
      'Contabilidad',
      'Derecho y Leyes',
      'Matemática, Economía y Finanzas',
      'Publicidad, Marketing y RRPP',
    ],
    area: [
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'arte y creatividad',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en UTEL Universidad Tecnológica Latinoamericana en Línea',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Políticas',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Recursos Humanos y Riesgo Laboral',
      'Seguridad, Criminología y Estudios Forenses',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Estatal Amazónica',
    carrera: [
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
    ],
    area: [
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de las Américas',
    carrera: [
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Políticas',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Imagen y Sonido',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'arte y creatividad',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Escuela Politécnica del Ejército',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Ciencias Políticas',
      'Comercio y Relaciones Internacionales',
      'Contabilidad',
      'Deportes y Educación Física',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Idiomas',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Escuela Politécnica Nacional',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Electrónica y Electricidad',
      'Física y Química',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en el Instituto de Altos Estudios Nacionales',
    carrera: ['Derecho y Leyes'],
    area: ['ciencias sociales'],
  },
  {
    nombreU:
      'Carreras Universitarias en Pontificia Universidad Católica del Ecuador',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Biológicas',
      'Ciencias Políticas',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Física y Química',
      'Historia y Geografía',
      'Hotelería, Gastronomía y Turismo',
      'Idiomas',
      'Ingeniería y Tecnología',
      'Lengua y Literatura',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Central del Ecuador',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Ciencias Políticas',
      'Ciencias Sociales y Humanidades',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
      'Seguridad, Criminología y Estudios Forenses',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad de Especialidades Turísticas',
    carrera: ['Hotelería, Gastronomía y Turismo'],
    area: ['ciencias sociales'],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de las Fuerzas Armadas',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Comercio y Relaciones Internacionales',
      'Deportes y Educación Física',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Seguridad, Criminología y Estudios Forenses',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad de Los Hemisferios',
    carrera: [
      'Administración y Administración Pública',
      'Arte y Bellas Artes',
      'Ciencias Políticas',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Derecho y Leyes',
      'Hotelería, Gastronomía y Turismo',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Iberoamericana del Ecuador',
    carrera: [
      'Comunicación, Periodismo, Cs de la Información',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Nutrición y Alimentación',
      'Salud y Medicina',
    ],
    area: [
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Internacional del Ecuador',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Derecho y Leyes',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Internacional SEK',
    carrera: [
      'Arquitectura Moda y Diseño',
      'Comercio y Relaciones Internacionales',
      'Derecho y Leyes',
      'Ingeniería y Tecnología',
      'Psicología y Ciencias del Comportamiento',
      'Salud y Medicina',
    ],
    area: [
      'arte y creatividad',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad San Francisco de Quito',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Arte y Bellas Artes',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Ciencias Políticas',
      'Ciencias Sociales y Humanidades',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Física y Química',
      'Hotelería, Gastronomía y Turismo',
      'Imagen y Sonido',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'ciencias sociales',
      'arte y creatividad',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Tecnológica Equinoccial',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Comercio y Relaciones Internacionales',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Publicidad, Marketing y RRPP',
      'Recursos Humanos y Riesgo Laboral',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'arte y creatividad',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Tecnológica Israel',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Contabilidad',
      'Educación',
      'Ingeniería y Tecnología',
      'Psicología y Ciencias del Comportamiento',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Estatal Península de Santa Elena',
    carrera: [
      'Administración y Administración Pública',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Contabilidad',
      'Deportes y Educación Física',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Regional Autónoma de los Andes',
    carrera: [
      'Administración y Administración Pública',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Hotelería, Gastronomía y Turismo',
      'Ingeniería y Tecnología',
      'Salud y Medicina',
      'Seguridad, Criminología y Estudios Forenses',
    ],
    area: [
      'económica,administrativa y financiera',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU: 'Carreras Universitarias en la Universidad Técnica de Ambato',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Agrarias',
      'Ciencias Biológicas',
      'Ciencias Sociales y Humanidades',
      'Comunicación, Periodismo, Cs de la Información',
      'Contabilidad',
      'Deportes y Educación Física',
      'Derecho y Leyes',
      'Educación',
      'Electrónica y Electricidad',
      'Hotelería, Gastronomía y Turismo',
      'Informática e Información',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Nutrición y Alimentación',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Salud y Medicina',
      'Veterinaria',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencias sociales',
      'ciencia y tecnología',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
  {
    nombreU:
      'Carreras Universitarias en la Universidad Tecnológica Indoamérica',
    carrera: [
      'Administración y Administración Pública',
      'Arquitectura Moda y Diseño',
      'Ciencias Sociales y Humanidades',
      'Contabilidad',
      'Derecho y Leyes',
      'Educación',
      'Ingeniería y Tecnología',
      'Matemática, Economía y Finanzas',
      'Medio Ambiente y Geología',
      'Psicología y Ciencias del Comportamiento',
      'Publicidad, Marketing y RRPP',
      'Recursos Humanos y Riesgo Laboral',
      'Salud y Medicina',
    ],
    area: [
      'económica,administrativa y financiera',
      'arte y creatividad',
      'ciencias sociales',
      'económica,administrativa y financiera',
      'ciencias sociales',
      'ciencias sociales',
      'ciencia y tecnología',
      'económica,administrativa y financiera',
      'ciencias ecológicas,biológicas y de salud',
      'ciencias sociales',
      'arte y creatividad',
      'ciencias sociales',
      'ciencias ecológicas,biológicas y de salud',
    ],
  },
];

const createUniversity = async (mongoDB, university) => {
  const { nombreU, carrera, area } = university;
  const questionId = await mongoDB.create('universityData', {
    nombreU,
    carrera,
    area,
  });

  return questionId;
};

const seedQuestions = async () => {
  try {
    const mongoDB = new MongoLib();
    const promises = uploadDataUny.map(async (question) => {
      const questionId = await createUniversity(mongoDB, question);
      debug(chalk.green(`Se subio todo hdp, id :${questionId}`));
    });
    await Promise.all(promises);
    return process.exit(0);
  } catch (error) {
    debug(chalk.red(error));
    process.exit(1);
  }
};

seedQuestions();
